$REPO = "Danino42/common-ground"

gh issue create --repo $REPO --title "US-01: Register with email and password" --body "## Epic`nAuthentication`n`n## User Story`nAs a facilitator, I want to register with email and password so I can have a personal account.`n`n## Acceptance Criteria`n- [ ] Facilitator can enter name, email, and password on the register form`n- [ ] Account is created and JWT token is returned on success`n- [ ] Duplicate email shows a clear error message`n- [ ] Password must be at least 8 characters`n- [ ] Empty fields show validation errors before submitting" --label "epic: auth"

gh issue create --repo $REPO --title "US-02: Login with credentials" --body "## Epic`nAuthentication`n`n## User Story`nAs a facilitator, I want to log in with my credentials so I can access my dashboard.`n`n## Acceptance Criteria`n- [ ] Facilitator can enter email and password to log in`n- [ ] Correct credentials return a JWT token and redirect to dashboard`n- [ ] Wrong credentials show a clear error message`n- [ ] Token is stored in localStorage or a cookie for session persistence`n- [ ] Logged-in facilitator stays logged in after page refresh" --label "epic: auth"

gh issue create --repo $REPO --title "US-03: Sign in with Google" --body "## Epic`nAuthentication`n`n## User Story`nAs a facilitator, I want a Sign in with Google option so I can log in without a password.`n`n## Acceptance Criteria`n- [ ] A Sign in with Google button appears on the login page`n- [ ] Clicking it opens Google OAuth flow`n- [ ] On success, facilitator is redirected to dashboard`n- [ ] If it is the first login, a new account is created automatically`n- [ ] If email already exists, the accounts are linked" --label "epic: auth"

gh issue create --repo $REPO --title "US-04: Secure password storage" --body "## Epic`nAuthentication`n`n## User Story`nAs a system, I want passwords to be hashed and stored securely so user data is protected.`n`n## Acceptance Criteria`n- [ ] Passwords are hashed with bcrypt before storing in MongoDB`n- [ ] Plain text passwords are never stored or logged`n- [ ] Password is never returned in any API response`n- [ ] JWT tokens expire after 24 hours`n- [ ] JWT secret key is stored in .env and never hardcoded" --label "epic: auth"

gh issue create --repo $REPO --title "US-05: Create card set manually" --body "## Epic`nCard Set Management`n`n## User Story`nAs a facilitator, I want to create a new card set manually so I can use it in my games.`n`n## Acceptance Criteria`n- [ ] Facilitator can enter a name, category, and list of card texts`n- [ ] Card set requires at least 3 cards to be saved`n- [ ] Saved card set appears in the facilitator's dashboard`n- [ ] Facilitator can add and remove cards before saving`n- [ ] Card set is stored in MongoDB linked to the facilitator's account" --label "epic: card-sets"

gh issue create --repo $REPO --title "US-06: Add cards to existing deck with AI" --body "## Epic`nCard Set Management`n`n## User Story`nAs a facilitator, I want to add cards to an existing deck using an AI prompt so I can expand it quickly.`n`n## Acceptance Criteria`n- [ ] Facilitator can open an existing deck and click Add with AI`n- [ ] Facilitator enters a prompt describing what cards to add`n- [ ] AI generates a list of suggested cards`n- [ ] Facilitator can accept, reject, or edit each suggestion individually`n- [ ] Accepted cards are appended to the existing deck and saved" --label "epic: card-sets"

gh issue create --repo $REPO --title "US-07: Generate new deck with AI" --body "## Epic`nCard Set Management`n`n## User Story`nAs a facilitator, I want to generate a completely new deck from an AI prompt so I can create content fast.`n`n## Acceptance Criteria`n- [ ] Facilitator can navigate to Create with AI page`n- [ ] Facilitator enters a deck name, category, and prompt`n- [ ] AI generates 8-12 card statements based on the prompt`n- [ ] Facilitator can regenerate if not satisfied`n- [ ] Facilitator can edit individual cards before saving`n- [ ] Saved deck appears in the dashboard" --label "epic: card-sets"

gh issue create --repo $REPO --title "US-08: Translate deck with AI" --body "## Epic`nCard Set Management`n`n## User Story`nAs a facilitator, I want to translate an entire deck to another language using AI so I can run multilingual sessions.`n`n## Acceptance Criteria`n- [ ] Facilitator can select a deck and click Translate`n- [ ] A list of target languages is shown to choose from`n- [ ] AI translates all card texts to the selected language`n- [ ] Facilitator can review translations before saving`n- [ ] Translated deck is saved as a new separate deck with language indicated" --label "epic: card-sets"

gh issue create --repo $REPO --title "US-09: Share deck publicly" --body "## Epic`nCard Set Management`n`n## User Story`nAs a facilitator, I want to share my created decks publicly so others can use them.`n`n## Acceptance Criteria`n- [ ] Facilitator can toggle a deck to public from the dashboard`n- [ ] Public decks are submitted for profanity review before appearing in the library`n- [ ] Facilitator sees a pending review status after sharing`n- [ ] Facilitator can un-share a deck at any time`n- [ ] Shared deck shows the facilitator's username as author" --label "epic: card-sets"

gh issue create --repo $REPO --title "US-10: Browse community deck library" --body "## Epic`nCard Set Management`n`n## User Story`nAs a facilitator, I want to browse the community deck library so I can use decks made by others.`n`n## Acceptance Criteria`n- [ ] Facilitator can navigate to the community library`n- [ ] All approved public decks are listed with name, category, and author`n- [ ] Facilitator can search by name or category`n- [ ] Facilitator can preview cards in a deck before using it`n- [ ] Facilitator can copy a community deck to their own collection" --label "epic: card-sets"

gh issue create --repo $REPO --title "US-11: Profanity check on shared decks" --body "## Epic`nCard Set Management`n`n## User Story`nAs a system, I want shared decks to pass a profanity check before publishing so the library stays appropriate.`n`n## Acceptance Criteria`n- [ ] When a deck is submitted for sharing, each card text is checked automatically`n- [ ] Decks with flagged content are rejected and the facilitator is notified`n- [ ] Facilitator sees which cards were flagged`n- [ ] Facilitator can edit and resubmit after rejection`n- [ ] Approved decks appear in the community library within a reasonable time" --label "epic: card-sets"

gh issue create --repo $REPO --title "US-12: Edit username and password" --body "## Epic`nFacilitator Profile`n`n## User Story`nAs a facilitator, I want to view and edit my username and password so I can keep my account up to date.`n`n## Acceptance Criteria`n- [ ] Facilitator can view their current name and email on the profile page`n- [ ] Facilitator can update their name and save it`n- [ ] Facilitator can change their password by entering current and new password`n- [ ] Wrong current password shows a clear error`n- [ ] New password must meet minimum length requirement`n- [ ] Changes are saved to MongoDB and reflected immediately" --label "epic: profile"

gh issue create --repo $REPO --title "US-13: Upload and delete profile picture" --body "## Epic`nFacilitator Profile`n`n## User Story`nAs a facilitator, I want to upload and delete my profile picture so I can personalize my account.`n`n## Acceptance Criteria`n- [ ] Facilitator can upload an image file as profile picture`n- [ ] Image is resized and stored`n- [ ] Profile picture appears in the header and profile page`n- [ ] Facilitator can delete their profile picture and revert to initials avatar`n- [ ] Only image file types are accepted (jpg, png, webp)" --label "epic: profile"

gh issue create --repo $REPO --title "US-14: View account statistics" --body "## Epic`nFacilitator Profile`n`n## User Story`nAs a facilitator, I want to see statistics about my hosted games and shared card sets so I can track my activity.`n`n## Acceptance Criteria`n- [ ] Profile page shows total number of games hosted`n- [ ] Profile page shows total number of players across all sessions`n- [ ] Profile page shows number of card sets created`n- [ ] Profile page shows number of card sets shared publicly`n- [ ] Stats update automatically after each game session ends" --label "epic: profile"

gh issue create --repo $REPO --title "US-15: Launch a game" --body "## Epic`nGame Hosting`n`n## User Story`nAs a facilitator, I want to launch a game by clicking Launch Game with a chosen card set so a QR code and lobby code appear.`n`n## Acceptance Criteria`n- [ ] Facilitator can select a card set and click Launch Game`n- [ ] A unique 6-digit lobby code is generated and displayed`n- [ ] A QR code pointing to the player join URL is displayed`n- [ ] Lobby code is stored in MongoDB as an active game session`n- [ ] Facilitator can copy the lobby code with one click" --label "epic: game-hosting"

gh issue create --repo $REPO --title "US-16: Choose game mode" --body "## Epic`nGame Hosting`n`n## User Story`nAs a facilitator, I want to choose between 3 game modes when creating a session so I can pick the right format.`n`n## Acceptance Criteria`n- [ ] Facilitator sees 3 game mode options when creating a session`n- [ ] Each mode has a clear name and short description`n- [ ] Selected mode is highlighted visually`n- [ ] Game mode is stored with the session in MongoDB`n- [ ] Facilitator cannot start the game without selecting a mode" --label "epic: game-hosting"

gh issue create --repo $REPO --title "US-17: Gamemode 1 - Circle" --body "## Epic`nGame Hosting`n`n## User Story`nAs a facilitator, I want Gamemode 1 to display cards one by one on a shared screen so players can discuss each one.`n`n## Acceptance Criteria`n- [ ] Cards from the selected deck are displayed one at a time on the facilitator's screen`n- [ ] Facilitator can navigate to next and previous cards`n- [ ] A progress indicator shows current card number out of total`n- [ ] Players do not need to interact on their devices in this mode`n- [ ] Facilitator can end the session at any time" --label "epic: game-hosting"

gh issue create --repo $REPO --title "US-18: Gamemode 2 - Groups" --body "## Epic`nGame Hosting`n`n## User Story`nAs a facilitator, I want Gamemode 2 to divide players into groups of 5-6 so they can find common statements.`n`n## Acceptance Criteria`n- [ ] Players who have joined are divided into groups of 5-6 automatically`n- [ ] Each group is assigned a color and group number`n- [ ] Group assignments are displayed on the facilitator's screen`n- [ ] Each group can submit one common statement they all agree on`n- [ ] Facilitator can view all submitted statements on a results screen" --label "epic: game-hosting"

gh issue create --repo $REPO --title "US-19: Gamemode 3 - Swipe" --body "## Epic`nGame Hosting`n`n## User Story`nAs a facilitator, I want Gamemode 3 to let each player answer on their own device so I can collect individual data.`n`n## Acceptance Criteria`n- [ ] Each player sees cards on their own device after joining`n- [ ] Cards are shown in a random order unique per player`n- [ ] Players swipe right for Yes and left for No`n- [ ] All answers are sent to and stored in the backend`n- [ ] Facilitator screen shows how many players have finished swiping" --label "epic: game-hosting"

gh issue create --repo $REPO --title "US-20: YES/NO ratio results for Gamemode 3" --body "## Epic`nGame Hosting`n`n## User Story`nAs a facilitator, I want to see the YES/NO ratio for each card after a Gamemode 3 session so I can analyze results.`n`n## Acceptance Criteria`n- [ ] After all players finish, facilitator can view results`n- [ ] Each card shows the total YES and NO count`n- [ ] Results are displayed as both numbers and a percentage bar`n- [ ] Facilitator can export or screenshot the results`n- [ ] Results are stored in MongoDB for later reference" --label "epic: game-hosting"

gh issue create --repo $REPO --title "US-21: Similarity grouping after Gamemode 3" --body "## Epic`nGame Hosting`n`n## User Story`nAs a facilitator, I want players in Gamemode 3 to be grouped by similarity after swiping so I can form meaningful groups.`n`n## Acceptance Criteria`n- [ ] After all players finish swiping, an algorithm groups players by answer similarity`n- [ ] Groups are of 5-6 people with the most similar Yes/No patterns`n- [ ] Groups are displayed on the facilitator's screen with player names`n- [ ] Each group is assigned a color`n- [ ] Facilitator can trigger the grouping manually when ready" --label "epic: game-hosting"

gh issue create --repo $REPO --title "US-22: 10 simultaneous game sessions" --body "## Epic`nInfrastructure`n`n## User Story`nAs a system, I want at least 10 game sessions to run reliably at the same time.`n`n## Acceptance Criteria`n- [ ] At least 10 game sessions can run concurrently without errors`n- [ ] Each session is fully isolated`n- [ ] Server response time stays under 500ms under load`n- [ ] Sessions are cleaned up from MongoDB after they end`n- [ ] Load tested with a simulated scenario before demo" --label "epic: infrastructure"

gh issue create --repo $REPO --title "US-23: Join via QR code" --body "## Epic`nPlayer Experience`n`n## User Story`nAs a player, I want to join a game by scanning a QR code so I do not have to type anything.`n`n## Acceptance Criteria`n- [ ] QR code on the facilitator screen links directly to the join page with code pre-filled`n- [ ] Scanning the QR code on a mobile browser opens the join page`n- [ ] Player only needs to enter their name to join`n- [ ] Player is confirmed as joined and sees a waiting screen`n- [ ] Player count on the facilitator's screen updates in real time" --label "epic: player"

gh issue create --repo $REPO --title "US-24: Join via 6-digit code" --body "## Epic`nPlayer Experience`n`n## User Story`nAs a player, I want to join a game by typing a 6-digit code so I can join without scanning.`n`n## Acceptance Criteria`n- [ ] Player can navigate to the join page and type the 6-digit code manually`n- [ ] Code input auto-capitalizes and limits to 6 characters`n- [ ] Invalid code shows a clear error message`n- [ ] Valid code proceeds to name entry`n- [ ] Player is added to the game session in MongoDB" --label "epic: player"

gh issue create --repo $REPO --title "US-25: Play without logging in" --body "## Epic`nPlayer Experience`n`n## User Story`nAs a player, I want to play without logging in so there is no barrier to join.`n`n## Acceptance Criteria`n- [ ] No login or registration option is shown to players`n- [ ] Player only needs a name to join`n- [ ] Player session is temporary and tied only to the game session`n- [ ] Player data is not stored beyond the current game session`n- [ ] No cookies or tokens are set for players" --label "epic: player"

gh issue create --repo $REPO --title "US-26: Swipe cards left and right" --body "## Epic`nPlayer Experience`n`n## User Story`nAs a player in Gamemode 3, I want to swipe cards left for No and right for Yes so I can answer intuitively.`n`n## Acceptance Criteria`n- [ ] Cards can be dragged left or right on touch screens`n- [ ] Dragging right shows a green YEAH indicator`n- [ ] Dragging left shows a red NOPE indicator`n- [ ] Releasing past the threshold commits the answer`n- [ ] Releasing before the threshold snaps the card back" --label "epic: player"

gh issue create --repo $REPO --title "US-27: Tap buttons as alternative to swiping" --body "## Epic`nPlayer Experience`n`n## User Story`nAs a player in Gamemode 3, I want to tap X or tick buttons as an alternative to swiping so I can answer without gestures.`n`n## Acceptance Criteria`n- [ ] X and tick buttons are visible below each card`n- [ ] Tapping tick has the same effect as swiping right`n- [ ] Tapping X has the same effect as swiping left`n- [ ] Buttons work correctly on both mobile and desktop`n- [ ] Buttons do not interfere with the drag gesture" --label "epic: player"

gh issue create --repo $REPO --title "US-28: See personal Yes/No summary at end" --body "## Epic`nPlayer Experience`n`n## User Story`nAs a player, I want to see my total Yes and No count at the end so I can reflect on my answers.`n`n## Acceptance Criteria`n- [ ] After swiping all cards a summary screen appears automatically`n- [ ] Summary shows total number of Yes and No answers`n- [ ] Summary screen shows a friendly completion message`n- [ ] Player sees a waiting for game to start indicator after finishing`n- [ ] Summary is shown only after all cards have been answered" --label "epic: player"

gh issue create --repo $REPO --title "US-29: WebSockets for real-time sync" --body "## Epic`nInfrastructure`n`n## User Story`nAs a developer, I want the backend to use WebSockets for real-time game state so all players stay in sync.`n`n## Acceptance Criteria`n- [ ] Player joining a session is reflected on the facilitator screen in real time`n- [ ] When all players finish swiping, facilitator is notified automatically`n- [ ] WebSocket connection is re-established if dropped`n- [ ] Each game session has its own isolated WebSocket room`n- [ ] WebSocket server handles at least 10 concurrent sessions" --label "epic: infrastructure"

gh issue create --repo $REPO --title "US-30: Similarity grouping algorithm" --body "## Epic`nInfrastructure`n`n## User Story`nAs a developer, I want the similarity grouping algorithm implemented for Gamemode 3 so players are matched meaningfully.`n`n## Acceptance Criteria`n- [ ] Algorithm compares each player's Yes/No answer vector against all others`n- [ ] Uses cosine similarity or Jaccard index to compute closeness`n- [ ] Players are grouped to maximize intra-group similarity`n- [ ] Groups are balanced in size (5-6 people)`n- [ ] Algorithm runs in under 2 seconds for up to 60 players" --label "epic: infrastructure"

gh issue create --repo $REPO --title "US-31: Mobile browser compatibility" --body "## Epic`nInfrastructure`n`n## User Story`nAs a developer, I want the app to work on mobile browsers without installing anything so players can join from any phone.`n`n## Acceptance Criteria`n- [ ] App works on iOS Safari and Android Chrome without installing anything`n- [ ] Touch gestures work correctly on all screen sizes`n- [ ] No horizontal scrolling on mobile screens`n- [ ] Text is readable without zooming on a standard phone screen`n- [ ] QR code scan opens app correctly on both iOS and Android" --label "epic: infrastructure"